#!/bin/bash

############################################################
# Copyright (c) 2015 Jonathan Yantis
# Released under the MIT license
############################################################

/usr/bin/initalize-graphics

# Launch the X server
/usr/bin/X

# vim:set ts=2 sw=2 et:
